name: ci

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint
      - run: bun run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build

  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 25
          - 24
          - 22
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: bun install --production
      - run: bun run build
      - run: node ./dist/card.js

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [lint, test, build, smoke-test]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: bun install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SR_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
